supla:
  port: 2016
  host: '192.168.1.216'
  email: 'lukaszbek@gmail.com'
  protocol_version: 10

pushover:
  user: 'ukfou5nbqy39uf3p99qvai9k3i2q9m'
  token: 'a2ms5m2viknux6svj1uo2nfvyeno23'

notifications:
  - trigger: 'onchange'
    condition: '%channel_90% == 1'
    message: 'kitchen lamp is on!'

  - trigger: 'ontime'
    time: '* * 22 * * *'
    condition: '%channel_2% == 1 || %channel_3% == 1'
    message: 'porch lights are on!'
  
  - trigger: 'onchange'
    condition: '%channel_34% > 8.5'
    message: 'it s hot!'
